import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">

      <body className={inter.className}>

        <div className="grid">

          <header className="bg-slate-950 p-4 grid place-items-center">

            <div className="w-[1152px] flex justify-between">

              <div className="flex flex-col gap-2">
                <p className="text-slate-200 text-xl font-bold">SSR e CSR</p>
                <p className=" text-slate-400">Este site é SSR</p>
              </div>

              <nav className="border-2 border-slate-200 grid p-1">
                <ul className="flex text-slate-200 p-1">
                  <li className="nav-item"><a href="/">Home</a></li>
                  <li className="nav-item"><a href="/">Web</a></li>
                  <li className="nav-item"><a href="/">SSR</a></li>
                  <li className="nav-item"><a href="/">CSR</a></li>
                  <li className="nav-item"><a href="/">SEO</a></li>
                </ul>
              </nav>

            </div>

          </header>

          <div className="min-h-[100vh] w-full flex justify-center bg-slate-200">
            <div className="max-w-6xl bg-white p-4 shadow-lg">
              {children}
            </div>
          </div>

          <footer className="bg-slate-950 p-4 grid place-items-center">

            <div className="w-[1152px] flex justify-between">
              <div className="flex flex-col gap-2">
                <p className="text-slate-200 text-xl font-bold">SSR e CSR</p>
                <p className=" text-slate-400">Este site é SSR</p>
              </div>

              <div className="grid place-items-center">
                <p className="text-slate-200 font-bold">Leonardo de Souza Bezerra</p>
              </div>
            </div>

          </footer>

        </div>

      </body>

    </html>
  );
}
